-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 18:40:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chatapp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chatapp` ;

-- -----------------------------------------------------
-- Schema chatapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatapp` DEFAULT CHARACTER SET utf8 ;
USE `chatapp` ;

-- -----------------------------------------------------
-- Table `chatapp`.`tb_conversations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatapp`.`tb_conversations` ;

CREATE TABLE IF NOT EXISTS `chatapp`.`tb_conversations` (
  `conversation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `requested_deletion` TINYINT(1) NOT NULL DEFAULT 0,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`conversation_id`),
  UNIQUE INDEX `conversation_id_UNIQUE` (`conversation_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatapp`.`tb_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatapp`.`tb_log` ;

CREATE TABLE IF NOT EXISTS `chatapp`.`tb_log` (
  `log_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `log_type` VARCHAR(45) NOT NULL,
  `log_content` LONGTEXT NOT NULL,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  UNIQUE INDEX `log_id_UNIQUE` (`log_id` ASC) VISIBLE,
  INDEX `log_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `log_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chatapp`.`tb_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatapp`.`tb_user_conversations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatapp`.`tb_user_conversations` ;

CREATE TABLE IF NOT EXISTS `chatapp`.`tb_user_conversations` (
  `user_conversations_id` INT(11) NOT NULL AUTO_INCREMENT,
  `conversation_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `is_creator` TINYINT(1) NOT NULL DEFAULT 0,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_conversations_id`),
  UNIQUE INDEX `user_conversations_id_UNIQUE` (`user_conversations_id` ASC) VISIBLE,
  INDEX `user_conversation_idx` (`user_id` ASC) VISIBLE,
  INDEX `user_conversations_conversation_idx` (`conversation_id` ASC) VISIBLE,
  CONSTRAINT `user_conversations_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `chatapp`.`tb_users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_conversations_conversation`
    FOREIGN KEY (`conversation_id`)
    REFERENCES `chatapp`.`tb_conversations` (`conversation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chatapp`.`tb_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chatapp`.`tb_users` ;

CREATE TABLE IF NOT EXISTS `chatapp`.`tb_users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 0,
  `requested_deletion` TINYINT(1) NOT NULL DEFAULT 0,
  `created_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS chatdb;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'chatdb' IDENTIFIED BY 'chatdb';

GRANT SELECT ON TABLE `chatapp`.* TO 'chatdb';
GRANT SELECT, INSERT, TRIGGER ON TABLE `chatapp`.* TO 'chatdb';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `chatapp`.* TO 'chatdb';
GRANT EXECUTE ON ROUTINE `chatapp`.* TO 'chatdb';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
